### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Nikodemsky** [FThompson/YouTubeUninterrupted#1]
Doesn't work anymore

**Comment by FThompson** [comment]
Thanks for reporting this.

From a quick test, I noticed that the extension doesn't activate if I browse to a video within YouTube. If I refresh the video page, the extension activates. I'm still waiting to see if the feature itself works, but at the very least, this is a bug I can work to fix.

Update: The extension works when it activates successfully (e.g. after a page refresh). I'll look into why it doesn't activate after navigating from within YouTube.

**Comment by Nikodemsky** [comment]
Thanks! i'll wait for the update.

**Comment by FThompson** [comment]
Version 1.1.2 fixes this issue and is live on the Chrome web store. Thanks!
